### ISSUE TITLE
Fix the cold days plots

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/climatehazards#10]
While on my visit to Montpellier in June 2024, I updated the flower endormancy plots for more species, I never worked on the cold temperature plots (e.g. leafindex_decompose_Fagus). I should make these for all species, including the days the maximum cold is exceeded (as well as current window near leafout). Based on our trace plots for Fagus (Feb 2024) we may not ascribe all the low leaf index days, but likely more.

* CHECK that I have notes on how to extract these numbers from the species file somewhere...

@vvandermeersch Can you tell me again how to check these from the species files? For example for Fagus:

>         <Frost>
>             <FHfrmax1>-6</FHfrmax1>
>             <FHfrmax2>-20</FHfrmax2>
>             <FHminfe>-5.3</FHminfe>
>             <FHminfl>-5.3</FHminfl>
>             <Te1>10</Te1>
>             <Te2>-16</Te2>
>             <FHtfemax>-8</FHtfemax>
>             <FHtflmax>-8</FHtflmax>
>             <FHpfemax>-12</FHpfemax>
>             <FHpflmax>-12</FHpflmax>
>             <NL1>10</NL1>
>             <NL2>16</NL2>
>         </Frost>

Is it -6 + -20 ?

**Comment by vvandermeersch** [comment]
@lizzieinvancouver Here's the description of each parameter:

```
<Frost>
        <FHfrmax1>-6</FHfrmax1> # related to fruit frost hardiness
        <FHfrmax2>-20</FHfrmax2> # related to fruit frost hardiness
        <FHminfe>-5.3</FHminfe> # minimum leaf frost hardiness
        <FHminfl>-5.3</FHminfl> # minimum flower frost hardiness (same as leaf because beech has mixed buds)
        <Te1>10</Te1> # related to frost hardiness induced by temperature 
        <Te2>-16</Te2> # related to frost hardiness induced by temperature 
        <FHtfemax>-8</FHtfemax> # maximum leaf frost hardiness induced by temperature
        <FHtflmax>-8</FHtflmax> # maximum flower frost hardiness induced by temperature
        <FHpfemax>-12</FHpfemax> # maximum leaf frost hardiness induced by photoperiod
        <FHpflmax>-12</FHpflmax> # maximum flower frost hardiness induced by photoperiod
        <NL1>10</NL1> # related to frost hardiness induced by photoperiod
        <NL2>16</NL2> # related to frost hardiness induced by photoperiod
</Frost>
```
So you want to look at `FHtfemax+FHpfemax` to get the maximum frost hardiness.

I am not responsible for the parameter names, but here's some explanations:
-`p` or `t` refers respectively to photoperiod and temperature in `FHt...` or `FHp...`
-`fr` stands for `fruit`, `fl` stands for `flower`, and `fe` stands for... _feuille_ (leaf in French)
You will find further information on the frost hardiness model in Leinonen (1996): https://doi.org/10.1006/anbo.1996.0178

Let me know if I can help!

(_and be careful not to disappear into the bowels of PHENOFIT..._)

**Comment by vvandermeersch** [comment]
@lizzieinvancouver I must correct my previous comment. Running analysis for another project, I noticed something Isabelle had forgotten (and that I hadn't seen in 3 years of PhD...):
`FHtfemax`, `FHpfemax`, etc., should rather be named `deltaFHtfemax`, etc. Indeed,  for example, `FHtfemax` represents the maximum **level of increase** of leaf frost hardiness induced by temperature.

Therefore, the maximum leaf frost hardiness is actually `FHminfe+FHtfemax+FHpfemax`.

Sorry for this mistake!

**Comment by lizzieinvancouver** [comment]
@vvandermeersch Alas -- for better or worse -- I have not worked on this, so no problem for me (alas).

**Comment by lizzieinvancouver** [comment]
Keeping some notes on what I am pulling here: 

- `Fagus_sylvatica_EvolLett2019.species` -- FHminfe: -5.3 + FHtfemax: -8 + FHpfemax: -12 (same values for flowers and leaves I believe) so -25.3
- `Pinus_sylvestris_ADuputie.species` -- see below, I think leaves are -5+-47+-18.5 and flowers are -10+-47+-18.5 so -70.5 and -75.5 (wow) 
- `Quercus_robur_ADuputie_Chuine.species` -- -37 (same values for flowers and leaves I believe; FHminfe is -7)

From `Pinus_sylvestris_ADuputie.species` : 
```
<FHminfe>-5</FHminfe>
<FHminfl>-10</FHminfl>
            <Te1>10</Te1>
            <Te2>-16</Te2>
            <FHtfemax>-47</FHtfemax>
            <FHtflmax>-47</FHtflmax>
            <FHpfemax>-18.5</FHpfemax>
            <FHpflmax>-18.5</FHpflmax>
```

**Comment by lizzieinvancouver** [comment]
Note to myself -- this is phenofitleafindexplots.R *and* I should fix the months here too I assume (see issue #11) as it looks like I use the current year only.

In phenofitleafindexplots.R, I have a good note on how to do across species, which is to functionalize the code I have ... with FHminfe and daysafter I wrote, but I would actually make FHminfe and something call maxcold be looked up based on species ... and add daysbefore to function, so the f(x) would be function(species, daysafter, daysbefore). My next steps then are:

- [x] Fix the months to wrap around to the October before
- [x] Add the maxcold
- [x] Make it work off a look-up table
- [x] Then functionalize what I have. 

I am not smart enough to do this today so will try tomorrow.

**Comment by lizzieinvancouver** [comment]
Okay, I did this, but should review the results with @vvandermeersch and Isabelle tomorrow. Also, why do we do this only for SD sims ... I assume only leafindex was confusing there, but if we want this to run ALL sims, now would be the time for me to update this code, while I am remember it.

**Comment by lizzieinvancouver** [comment]
Done.
