### ISSUE TITLE
check years on ERALAND5 data

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/climatehazards#2]
@vvandermeersch I thought I had the update PET and PRE for the new (as of early April) sites, but I noticed today the sites don't seem updated for PET and PRE (but seem fine for the temperature files, altitude and WHC):

These are the sites I was expecting (I think) ...
```
> > d <- fread("~/Documents/git/projects/treegarden/misc/climatehazards/analyses/input/ERA5LAND/ERA5LAND_tmn_2007_dly.fit")
> > unique(d$V1)
> [1] 42.0 43.8 44.5 46.3 47.5 49.1 50.6 52.0 53.1
```

These are not (these are the old sites):
```
> > d <- fread("~/Documents/git/projects/treegarden/misc/climatehazards/analyses/input/ERA5LAND/ERA5LAND_pet_1982_dly.fit")
> > unique(d$V1)
> [1] 43.0 45.4 47.3 49.2 51.4 53.1 56.1 57.6 59.2
> > d <- fread("~/Documents/git/projects/treegarden/misc/climatehazards/analyses/input/ERA5LAND/ERA5LAND_pre_1982_dly.fit")
> > unique(d$V1)
> [1] 43.0 45.4 47.3 49.2 51.4 53.1 56.1 57.6 59.2
```
Can you check when you have time? 

See you next week!

**Comment by vvandermeersch** [comment]
@lizzieinvancouver sorry, I have the correct files in my local directory. I guess I made a mistake copying them on your disk. My bad!
Would you like me to upload them? Or do you want to wait until next week? 

See you!

**Comment by lizzieinvancouver** [comment]
@vvandermeersch Or maybe I copied them wrong? Either way, next week is soon enough! See you then.

**Comment by lizzieinvancouver** [comment]
@vvandermeersch This was my fault alone! It looks like I copied over the correct data to my data/ folder but failed to pull all the files to my analyses/input/ folder ... the new PHENOFIT error helped catch this. So all set! Thanks.
